### ISSUE TITLE
Unable to run a RabbitMq testcontainer (exits with error)

### ISSUE THREAD

**Issue by xtremekforever** [testcontainers/testcontainers-c#24]
If I try to run a RabbitMq image using the testcontainers-c library, it does not run and exits with the following error:

`/usr/local/bin/docker-entrypoint.sh: line 50: exec: : not found`

Here is the C code I used to try launching the container:

```c
#include <stdio.h>
#include <unistd.h>
#include "testcontainers-c.h"

#define RABBITMQ_IMAGE "rabbitmq:3.12.11-management-alpine"
int main() {
    printf("Using RabbitMq with the Testcontainers C binding:\n");

    printf("Creating new container: %s\n", RABBITMQ_IMAGE);
    int requestId = tc_new_container_request(RABBITMQ_IMAGE);
    tc_with_exposed_tcp_port(requestId, 5672);
    tc_with_exposed_tcp_port(requestId, 15672);
    struct tc_run_container_return ret = tc_run_container(requestId);
    int containerId = ret.r0;
    if (!ret.r1) {
        printf("Failed to run the container: %s\n", ret.r2);
        return -1;
    }
    printf("Launched container with ID: %d\n", containerId);

    sleep(5);
    char * logs = tc_get_container_log(containerId);
    printf("Received logs: %s\n", logs);

    return 0;
}
```

Would this be a problem of the testcontainers-go library, or perhaps how its being invoked? It would be nice to be able to use the C library to run a RabbitMQ image to run tests.

Also, here is the output of the C program above when running it on my machine (openSUSE Leap 15.6 host):

```
Using RabbitMq with the Testcontainers C binding:
Creating new container: rabbitmq:3.12.11-management-alpine
2024/07/09 14:37:52 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.7-ce
  API Version: 1.43
  Operating System: openSUSE Leap 15.6
  Total Memory: 64013 MB
2024/07/09 14:37:52 🐳 Creating container for image docker.io/testcontainers/ryuk:0.5.1
2024/07/09 14:37:52 ✅ Container created: 9c5655466cbe
2024/07/09 14:37:52 🐳 Starting container: 9c5655466cbe
2024/07/09 14:37:52 ✅ Container started: 9c5655466cbe
2024/07/09 14:37:52 🚧 Waiting for container id 9c5655466cbe image: docker.io/testcontainers/ryuk:0.5.1. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/07/09 14:37:52 🐳 Creating container for image rabbitmq:3.12.11-management-alpine
2024/07/09 14:37:52 ✅ Container created: ffe15b2ab23c
2024/07/09 14:37:52 🐳 Starting container: ffe15b2ab23c
2024/07/09 14:37:53 ✅ Container started: ffe15b2ab23c
Launched container with ID: 0
Received logs: /usr/local/bin/docker-entrypoint.sh: line 50: exec: : not found
```

**Comment by oleg-nenashev** [comment]
According to https://github.com/rabbitmq/rabbitmq-server/blob/main/packaging/docker-image/docker-entrypoint.sh#L50 , the RabbitMQ server receives the command from the invocation CLI arguments. In your case, it is empty

The base image passes the default CMD in https://github.com/rabbitmq/rabbitmq-server/blob/main/packaging/docker-image/Dockerfile#L315 . It looks like we do not respect the default `CMD`. Mostly likely it is an issue in Testcontainers for Go @mdelapenya . 

An easy workaround would be to pass the command explicitly

**Comment by mdelapenya** [comment]
Mmmm is it using the rabbitmq module, or a plain generic container? If using the rabbitmq module, we are not overriding it: https://github.com/testcontainers/testcontainers-go/blob/main/modules/rabbitmq/rabbitmq.go#L77-L95

If the case is using generic container, where the user has full control of the underlying image, I'm not sure where the CMD is overriden.

**Comment by xtremekforever** [comment]
This is just using the generic container. Based on looking at the rabbitmq module from the testcontainers-go library, I found out that the issue is that the `tc_new_container_request` method in testcontainers-c passes `Cmd` with an empty string:

```go
	req := testcontainers.ContainerRequest{
		Image: C.GoString(image),
		Cmd:   []string{""},
	}
```
If I remove the Cmd line, the rabbitmq container works. I can pull request this fix if it would be useful.

**Comment by oleg-nenashev** [comment]
@xtremekforever Yes, it would definitely be a good change, thank you!
